// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL2VBsEoA53u_QeyG5FRlZONoB9FxW2cA',
    appId: '1:178222818949:web:9e343c7e1626356852ebec',
    messagingSenderId: '178222818949',
    projectId: 'yl-orders-b7b52',
    authDomain: 'yl-orders-b7b52.firebaseapp.com',
    storageBucket: 'yl-orders-b7b52.appspot.com',
    measurementId: 'G-60K7FZ74LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlK2HFMdi76Lwt08R0WU0_ADHUjEwB91o',
    appId: '1:178222818949:android:7531c13bf0fe731652ebec',
    messagingSenderId: '178222818949',
    projectId: 'yl-orders-b7b52',
    storageBucket: 'yl-orders-b7b52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHq0M8uG0N8bl60TMCvHya4cmvtpKKU_I',
    appId: '1:178222818949:ios:7ba5438ef6e98c3f52ebec',
    messagingSenderId: '178222818949',
    projectId: 'yl-orders-b7b52',
    storageBucket: 'yl-orders-b7b52.appspot.com',
    iosBundleId: 'com.example.ylorders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHq0M8uG0N8bl60TMCvHya4cmvtpKKU_I',
    appId: '1:178222818949:ios:b82827333c7e39ea52ebec',
    messagingSenderId: '178222818949',
    projectId: 'yl-orders-b7b52',
    storageBucket: 'yl-orders-b7b52.appspot.com',
    iosBundleId: 'com.example.ylorders.RunnerTests',
  );
}
